name: graphslot
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.0=py37hd667e15_1
  - cryptography=37.0.1=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=21.2.2=py37h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py37_1
  - python=3.7.13=h12debd9_0
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.11.0=py37_cu113
  - typing_extensions=4.1.1=pyh06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - apache-beam==2.48.0
      - appdirs==1.4.4
      - argcomplete==3.1.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==23.1.0
      - boto==2.49.0
      - cached-property==1.5.2
      - cachetools==5.3.1
      - chardet==5.2.0
      - charset-normalizer==3.2.0
      - chex==0.1.5
      - click==8.1.7
      - cloudpickle==2.2.1
      - clu==0.0.9
      - contextlib2==21.6.0
      - crcmod==1.7
      - cycler==0.11.0
      - dill==0.3.1.1
      - dm-tree==0.1.8
      - dnspython==2.3.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - easydict==1.11
      - etils==0.9.0
      - exceptiongroup==1.1.3
      - fastavro==1.8.0
      - fasteners==0.18
      - flatbuffers==23.5.26
      - flax==0.6.4
      - fonttools==4.38.0
      - freetype-py==2.4.0
      - frozenlist==1.3.3
      - future==0.18.3
      - gast==0.4.0
      - gcs-oauth2-boto-plugin==3.0
      - gitdb==4.0.10
      - gitpython==3.1.35
      - google-apitools==0.5.32
      - google-auth==2.22.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - google-reauth==0.1.1
      - googleapis-common-protos==1.60.0
      - grpcio==1.58.0
      - gsutil==5.25
      - h5py==3.8.0
      - hdfs==2.7.3
      - hsluv==5.0.4
      - httplib2==0.20.4
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - iniconfig==2.0.0
      - jax==0.3.25
      - jaxlib==0.3.25
      - keras==2.11.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.4.4
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - matplotlib==3.5.3
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - monotonic==1.6
      - msgpack==1.0.5
      - mttkinter==0.6.1
      - multidict==6.0.4
      - networkx==2.6.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - objsize==0.6.1
      - opencv-python==4.8.0.76
      - opt-einsum==3.3.0
      - optax==0.1.4
      - orbax==0.1.0
      - orjson==3.9.7
      - packaging==23.1
      - pathtools==0.1.2
      - pillow==9.5.0
      - pluggy==1.2.0
      - promise==2.3
      - proto-plus==1.22.3
      - protobuf==3.20.3
      - psutil==5.9.5
      - pyarrow==11.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pydot==1.4.2
      - pygments==2.16.1
      - pymongo==4.6.0
      - pyparsing==3.1.1
      - pytest==7.4.2
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyu2f==0.1.5
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - retry-decorator==1.1.1
      - rich==13.5.2
      - rsa==4.7.2
      - scikit-image==0.19.3
      - scipy==1.7.3
      - sentry-sdk==1.30.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-cpu==2.11.0
      - tensorflow-datasets==4.8.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - tensorflow-metadata==1.12.0
      - tensorstore==0.1.28
      - termcolor==2.3.0
      - tifffile==2021.11.2
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==1.13.1
      - torchvision==0.14.1
      - tqdm==4.66.1
      - urllib3==1.26.16
      - vispy==0.13.0
      - wandb==0.15.10
      - werkzeug==2.2.3
      - wrapt==1.15.0
      - yarl==1.9.2
      - zipp==3.15.0
      - zstandard==0.21.0
prefix: ./anaconda3/envs/graphslot
